image: rust:latest

stages:
  - test
  - build-pages
  - deploy

tests:
  stage: test
  script:
    - cargo test --verbose
  only:
    - branches

# Build Page stage: Generate documentation
doc:
  stage: build-pages
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc
    expire_in: 1 hour
  only:
    - main

# Deploy stage: Publish docs to GitLab Pages
pages:
  stage: deploy
  dependencies:
    - doc
  script:
    - mkdir public
    - cp -r target/doc/* public/
  artifacts:
    paths:
      - public
  only:
    - main