image: rust:latest

stages:
  - test
  - build-pages-rustdoc
  - deploy-swagger
  - deploy-rustdoc

tests:
  stage: test
  script:
    - cargo test --verbose
  only:
    - branches

# Build Page stage: Generate documentation
doc-rustdoc:
  stage: build-pages-rustdoc
  script:
    - cargo doc
    - mkdir swagger
    - cargo run -- generate-swagger > ./swagger/openapi.json
  artifacts:
    paths:
      - target/doc
      - swagger
    expire_in: 1 hour
  only:
    - branches

pages-swagger:
  image: node:latest
  stage: deploy-swagger
  dependencies:
    - doc-rustdoc
  script:
    - npm install -g redoc-cli
    - redoc-cli bundle -o public/index.html swagger/openapi.json
  artifacts:
    paths:
      - public
  only:
    - branches

# Deploy stage: Publish docs to GitLab Pages
pages-rustdoc:
  image: alpine:latest
  stage: deploy-rustdoc
  dependencies:
    - doc-rustdoc
  script:
    - mkdir public
    - cp -r target/doc/* public/
  artifacts:
    paths:
      - public
  only:
    - branches