image: rust:latest

stages:
  - test
  - docs
  - build
  - release
  - deploy

include:
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/release.yml
  - local: .gitlab-ci/deploy.yml

tests:
  stage: test
  script:
    - cargo test --verbose
  except:
    - tags

# Build Page stage: Generate documentation
doc-rustdoc:
  stage: docs
  dependencies:
    - tests
  script:
    - cargo doc
    - mkdir swagger
    - cargo run -- generate-swagger > ./swagger/openapi.json
  artifacts:
    paths:
      - target/doc
      - swagger
    expire_in: 1 hour
  only:
    - main

# Deploy stage: Publish docs to GitLab Pages
pages:
  image: alpine:latest
  stage: deploy
  needs:
    - job: pages-swagger
      artifacts: true
    - job: doc-rustdoc
      artifacts: false
  script:
    - mkdir public
    - mkdir public/rustdoc
    - mkdir public/swagger
    - cp -r target/doc/* public/rustdoc/
    - mv ./public-swagger/* public/swagger/
  artifacts:
    paths:
      - public
  only:
    - main

pages-swagger:
  image: node:latest
  stage: docs
  needs:
    - job: doc-rustdoc
      artifacts: true
  script:
    - mkdir public-swagger
    - npx @redocly/cli build-docs -o public-swagger/index.html swagger/openapi.json
  artifacts:
    paths:
      - public-swagger
      - target
  only:
    - main