image: rust:latest

stages:
  - build
  - deploy

# Build stage: Generate documentation
doc:
  stage: build
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc
    expire_in: 1 hour
  only:
    - branches

# Deploy stage: Publish docs to GitLab Pages
pages:
  stage: deploy
  dependencies:
    - doc
  script:
    - mkdir public
    - cp -r target/doc/* public/
  artifacts:
    paths:
      - public
  only:
    - branches