image: rust:latest

stages:
  - test
  - docs
  - build
  - release
  - deploy

include:
  - local: .gitlab-ci/.gitlab-ci.build.yml
  - local: .gitlab-ci/.gitlab-ci.release.yml
  - local: .gitlab-ci/.gitlab-ci.deploy.yml

tests:
  stage: test
  before_script:
    - apt update && apt install -y jq
  script:
    - echo "Checking if pipeline for this branch has already ran"
    - curl -s -X GET https://git.al3xdev.com/api/v4/projects/187/releases | jq --arg target_commit "${CI_COMMIT_SHA}" 'any(.[]; .commit.id == $target_commit)' > .pipeline_re_run_status
    - if [ $(cat ./.pipeline_re_run_status) == "true" ]; then echo "Skipping because this is a re-run"; exit 0; fi
    - if [ ${SKIP_BUILD} == "true" ]; then echo "Skipping because of SKIP_BUILD set to true"; exit 0; fi
    - cargo test --verbose
  artifacts:
    paths:
      - .pipeline_re_run_status
  except:
    - tags

# Build Page stage: Generate documentation
doc-rustdoc:
  stage: docs
  dependencies:
    - tests
  needs:
    job: tests
    artifacts: true
  script:
    - if [ $(cat ./.pipeline_re_run_status) == "true" ]; then echo "Skipping because this is a re-run"; exit 0; fi
    - if [ ${SKIP_BUILD} == "true" ]; then echo "Skipping because of SKIP_BUILD set to true"; exit 0; fi
    - cargo doc --no-deps
    - mkdir swagger
    - cargo run -- generate-swagger > ./swagger/openapi.json
  artifacts:
    paths:
      - target/doc
      - swagger
      - .pipeline_re_run_status
    expire_in: 1 hour
  only:
    - main

# Deploy stage: Publish docs to GitLab Pages
pages:
  image: alpine:latest
  stage: deploy
  needs:
    - job: pages-swagger
      artifacts: true
    - job: doc-rustdoc
      artifacts: false
  script:
    - if [ $(cat ./.pipeline_re_run_status) == "true" ]; then echo "Skipping because this is a re-run"; exit 0; fi
    - if [ ${SKIP_BUILD} == "true" ]; then echo "Skipping because of SKIP_BUILD set to true"; exit 0; fi
    - mkdir public
    - mkdir public/rustdoc
    - mkdir public/swagger
    - cp -r target/doc/* public/rustdoc/
    - mv ./public-swagger/* public/swagger/
  artifacts:
    paths:
      - public
  only:
    - main

pages-swagger:
  image: node:latest
  stage: docs
  needs:
    - job: doc-rustdoc
      artifacts: true
  script:
    - if [ $(cat ./.pipeline_re_run_status) == "true" ]; then echo "Skipping because this is a re-run"; exit 0; fi
    - if [ ${SKIP_BUILD} == "true" ]; then echo "Skipping because of SKIP_BUILD set to true"; exit 0; fi
    - mkdir public-swagger
    - npx @redocly/cli build-docs -o public-swagger/index.html swagger/openapi.json
  artifacts:
    paths:
      - public-swagger
      - target
      - .pipeline_re_run_status
  only:
    - main