image: rust:latest

stages:
  - test
  - build-pages-rustdoc
  - build-pages-swagger
  - deploy-pages

tests:
  stage: test
  script:
    - cargo test --verbose
  only:
    - branches

# Build Page stage: Generate documentation
doc-rustdoc:
  stage: build-pages-rustdoc
  script:
    - cargo doc
    - mkdir swagger
    - cargo run -- generate-swagger > ./swagger/openapi.json
  artifacts:
    paths:
      - target/doc
      - swagger
    expire_in: 1 hour
  only:
    - branches

# Deploy stage: Publish docs to GitLab Pages
pages:
  image: alpine:latest
  stage: deploy-pages
  dependencies:
    - pages-swagger
  script:
    - mkdir public
    - mkdir public/rustdoc
    - mkdir public/swagger
    - cp -r target/doc/* public/rustdoc/
    - mv ./public-swagger/* public/swagger/
  artifacts:
    paths:
      - public
  only:
    - branches

pages-swagger:
  image: node:latest
  stage: build-pages-swagger
  dependencies:
    - doc-rustdoc
  script:
    - mkdir public-swagger
    - npx @redocly/cli build-docs -o public-swagger/index.html swagger/openapi.json
  artifacts:
    paths:
      - public-swagger
      - target
  only:
    - branches