[package]
name = "mycondominium-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
chrono = "0.4.40"
diesel = { version = "2.2.8", features = ["postgres", "uuid", "chrono", "serde_json"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15.7"
serde = { version =  "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.0", features = ["full"] }
uuid = { version =  "1.15.1", features = ["serde", "v4"] }
