[target.x86_64-pc-windows-gnu]
image = "registry.al3xdev.com:443/puc/software-engineering-v/mycondominium-backend:cross-rs-x86_64-pc-windows-gnu-latest"
[target.x86_64-unknown-linux-gnu]
image = "registry.al3xdev.com:443/puc/software-engineering-v/mycondominium-backend:cross-rs-x86_64-unknown-linux-gnu-latest"
[target.x86_64-unknown-linux-musl]
image = "registry.al3xdev.com:443/puc/software-engineering-v/mycondominium-backend:cross-rs-x86_64-unknown-linux-musl-latest"