[target.x86_64-pc-windows-gnu]
image = "registry.al3xdev.com:443/puc/software-engineering-v/mycondominium-backend:cross-rs-x86_64-pc-windows-gnu-latest"
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "link-arg=--sysroot=/usr/x86_64-w64-mingw32"]
[target.x86_64-unknown-linux-gnu]
image = "registry.al3xdev.com:443/puc/software-engineering-v/mycondominium-backend:cross-rs-x86_64-unknown-linux-gnu-latest"
[target.x86_64-unknown-linux-musl]
image = "registry.al3xdev.com:443/puc/software-engineering-v/mycondominium-backend:cross-rs-x86_64-unknown-linux-musl-latest"