use actix_web::web;

pub fn admin_route() -> actix_web::Scope {
    web::scope("/api/admin")
        .route(
            "/list",
            web::get().to(crate::services::admin_service::get_admin::get_admins),
        )
        .route(
            "/get/{id}",
            web::get().to(crate::services::admin_service::get_admin::get_admin_by_id),
        )
        .route(
            "/new",
            web::post().to(crate::services::admin_service::upsert_admin::new_admin),
        )
        .route(
            "/update/{id}",
            web::put().to(crate::services::admin_service::upsert_admin::update_admin),
        )
        .route(
            "/delete/{id}",
            web::delete().to(crate::services::admin_service::upsert_admin::delete_admin),
        )
}

pub fn auth_route() -> actix_web::Scope {
    web::scope("/api/auth")
        .route(
            "/signin",
            web::post().to(crate::services::auth_service::sign_in::sign_in),
        )
        .route(
            "/auth",
            web::get().to(crate::services::auth_service::auth::auth),
        )
        .route(
            "/signout",
            web::get().to(crate::services::auth_service::auth::sign_out),
        )
        .route(
            "/new_admin_self_service",
            web::post()
                .to(crate::services::auth_service::new_admin_self_service::new_admin_self_service),
        )
        .route(
            "/request_password_reset",
            web::post().to(crate::services::auth_service::password_reset::request_password_reset),
        )
        .route(
            "/password_reset",
            web::post().to(crate::services::auth_service::password_reset::password_reset),
        )
}

pub fn common_area_route() -> actix_web::Scope {
    web::scope("/api/common_area")
        .route(
            "/list",
            web::get().to(crate::services::common_area_service::get_common_area::get_common_areas),
        )
        .route(
            "/get/{id}",
            web::get()
                .to(crate::services::common_area_service::get_common_area::get_common_area_by_id),
        )
        .route(
            "/new",
            web::post()
                .to(crate::services::common_area_service::upsert_common_area::new_common_area),
        )
        .route(
            "/update/{id}",
            web::put()
                .to(crate::services::common_area_service::upsert_common_area::update_common_area),
        )
        .route(
            "/delete/{id}",
            web::delete()
                .to(crate::services::common_area_service::upsert_common_area::delete_common_area),
        )
}

pub fn community_route() -> actix_web::Scope {
    web::scope("/api/community")
        .route(
            "/list",
            web::get().to(crate::services::community_service::get_community::get_communities),
        )
        .route(
            "/get/{id}",
            web::get().to(crate::services::community_service::get_community::get_community_by_id),
        )
        .route(
            "/new",
            web::post().to(crate::services::community_service::upsert_community::new_community),
        )
        .route(
            "/update/{id}",
            web::put().to(crate::services::community_service::upsert_community::update_community),
        )
        .route(
            "/delete/{id}",
            web::delete()
                .to(crate::services::community_service::upsert_community::delete_community),
        )
}

pub fn maintenance_schedule_route() -> actix_web::Scope {
    web::scope("/api/maintenance_schedule")
        .route(
            "/list",
            web::get().to(crate::services::maintenance_schedule_service::get_maintenance_schedule::get_maintenance_schedules),
        )
        .route(
            "/count/{status}",
            web::get().to(crate::services::maintenance_schedule_service::get_maintenance_schedule::count_maintenance_schedule),
        )
        .route(
            "/get/{id}",
            web::get().to(crate::services::maintenance_schedule_service::get_maintenance_schedule::get_maintenance_schedule_by_id),
        )
        .route(
            "/new",
            web::post().to(crate::services::maintenance_schedule_service::upsert_maintenance_schedule::new_maintenance_schedule),
        )
        .route(
            "/update/{id}",
            web::put().to(crate::services::maintenance_schedule_service::upsert_maintenance_schedule::update_maintenance_schedule),
        )
        .route(
            "/delete/{id}",
            web::delete().to(crate::services::maintenance_schedule_service::upsert_maintenance_schedule::delete_maintenance_schedule),
        )
}

pub fn parcel_route() -> actix_web::Scope {
    web::scope("/api/parcel")
        .route(
            "/list",
            web::get().to(crate::services::parcel_service::get_parcel::get_parcels),
        )
        .route(
            "/get/{id}",
            web::get().to(crate::services::parcel_service::get_parcel::get_parcel_by_id),
        )
        .route(
            "/new",
            web::post().to(crate::services::parcel_service::upsert_parcel::new_parcel),
        )
        .route(
            "/update/{id}",
            web::put().to(crate::services::parcel_service::upsert_parcel::update_parcel),
        )
        .route(
            "/delete/{id}",
            web::delete().to(crate::services::parcel_service::upsert_parcel::delete_parcel),
        )
}

pub fn reservation_route() -> actix_web::Scope {
    web::scope("/api/reservation")
        .route(
            "/list",
            web::get().to(crate::services::reservation_service::get_reservation::get_reservations),
        )
        .route(
            "/get/{id}",
            web::get()
                .to(crate::services::reservation_service::get_reservation::get_reservation_by_id),
        )
        .route(
            "/new",
            web::post()
                .to(crate::services::reservation_service::upsert_reservation::new_reservation),
        )
        .route(
            "/update/{id}",
            web::put()
                .to(crate::services::reservation_service::upsert_reservation::update_reservation),
        )
        .route(
            "/delete/{id}",
            web::delete()
                .to(crate::services::reservation_service::upsert_reservation::delete_reservation),
        )
}

pub fn resident_route() -> actix_web::Scope {
    web::scope("/api/resident")
        .route(
            "/list",
            web::get().to(crate::services::resident_service::get_resident::get_residents),
        )
        .route(
            "/count",
            web::get().to(crate::services::resident_service::get_resident::count_resident),
        )
        .route(
            "/get/{id}",
            web::get().to(crate::services::resident_service::get_resident::get_resident_by_id),
        )
        .route(
            "/new",
            web::post().to(crate::services::resident_service::upsert_resident::new_resident),
        )
        .route(
            "/update/{id}",
            web::put().to(crate::services::resident_service::upsert_resident::update_resident),
        )
        .route(
            "/delete/{id}",
            web::delete().to(crate::services::resident_service::upsert_resident::delete_resident),
        )
        .route(
            "/invite/new",
            web::post().to(crate::services::resident_service::invite_resident::new_resident_invite),
        )
        .route(
            "/invite/list",
            web::get().to(crate::services::resident_service::invite_resident::get_resident_invites),
        )
        .route(
            "/invite/get/{id}",
            web::get()
                .to(crate::services::resident_service::invite_resident::get_resident_invite_by_id),
        )
        .route(
            "/invite/view/{key}",
            web::get()
                .to(crate::services::resident_service::invite_resident::get_resident_invite_by_key),
        )
        .route(
            "/invite/count",
            web::get()
                .to(crate::services::resident_service::invite_resident::count_resident_invite),
        )
        .route(
            "/invite/delete/{id}",
            web::delete()
                .to(crate::services::resident_service::invite_resident::delete_resident_invite),
        )
        .route(
            "/invite/signup",
            web::post()
                .to(crate::services::resident_service::invite_resident::new_resident_by_invite),
        )
}

pub fn vehicle_route() -> actix_web::Scope {
    web::scope("/api/vehicle")
        .route(
            "/list",
            web::get().to(crate::services::vehicle_service::get_vehicle::get_vehicles),
        )
        .route(
            "/get/{id}",
            web::get().to(crate::services::vehicle_service::get_vehicle::get_vehicle_by_id),
        )
        .route(
            "/new",
            web::post().to(crate::services::vehicle_service::upsert_vehicle::new_vehicle),
        )
        .route(
            "/update/{id}",
            web::put().to(crate::services::vehicle_service::upsert_vehicle::update_vehicle),
        )
        .route(
            "/delete/{id}",
            web::delete().to(crate::services::vehicle_service::upsert_vehicle::delete_vehicle),
        )
}
