database:
  url: postgres://<DATABASE_USER>:<DATABASE_PASSWORD>@127.0.0.1/<DATABASE_NAME>

smtp:
  host: "<SMTP_HOST>"
  port: "<SMTP_PORT>"
  username: "<SMTP_USERNAME>"
  password: "<SMTP_PASSWORD>"
  from: "<SMTP_FROM>"
  # Base url needed for handling email links for password recovery, user invitation, etc.
  # Example: "https://domain.com (Do not include trailing slash)
  base_url: "<BASE_URL>"

rabbitmq:
  host: "<RABBITMQ_HOST>"
  port: "<RABBITMQ_PORT>"
  username: "<RABBITMQ_USERNAME>"
  password: "<RABBITMQ_PASSWORD>"

minio:
  url: "<MINIO_URL>"
  bucket_name: "<MINIO_BUCKET_NAME>"
  access_key: "<MINIO_ACCESS_KEY>"
  secret_key: "<MINIO_SECRET_KEY>"

server:
  host: "127.0.0.1"
  port: "<SERVER_PORT>"
  cors_permissive: true

auth:
  token_expiration_days: <AUTH_TOKEN_EXPIRATION_DAYS>
  token_secret_key: "<AUTH_TOKEN_SECRET_KEY>"