stages:
  - release

release_nightly:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
    - if: $SKIP_BUILD
      when: never
  variables:
    LINUX_AMD64_GLIB_BIN: "mycondominium-server-linux-gnu-amd64"
    LINUX_AMD64_MUSL_BIN: "mycondominium-server-linux-musl-amd64"
  needs:
    job: build
    artifacts: true
  script:
    - if [ $(cat ./.pipeline_re_run_status) == "true" ]; then echo "Skipping because this is a re-run"; exit 0; fi
    - if [ ${SKIP_BUILD} == "true" ]; then echo "Skipping because of SKIP_BUILD set to true"; exit 0; fi
    - echo "LINUX_GNU_AMD64_BIN_URL=${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID_LINUX_AMD64_GNU}/artifacts/raw/target/x86_64-unknown-linux-gnu/release/mycondominium-backend" >> release_nightly.env
    - echo "LINUX_MUSL_AMD64_BIN_URL=${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID_LINUX_AMD64_MUSL}/artifacts/raw/target/x86_64-unknown-linux-musl/release/mycondominium-backend" >> release_nightly.env
    - echo "Running release_nightly for v${RUST_APP_VERSION}-${CI_COMMIT_SHORT_SHA}"
    - echo -e "## MyCondominium Nightly Build v${RUST_APP_VERSION}-${CI_COMMIT_SHORT_SHA}\n\n---\n\n### Changelog:\n\n${CI_COMMIT_MESSAGE}" > description.md
    - echo -e "Nightly Build v${RUST_APP_VERSION}-${CI_COMMIT_SHORT_SHA}" > release_name.txt
  artifacts:
    paths:
      - release_name.txt
  release:
    name: 'Nightly Build v${RUST_APP_VERSION}-${CI_COMMIT_SHORT_SHA}'
    description: description.md
    tag_name: 'nightly-v${RUST_APP_VERSION}-${CI_COMMIT_SHORT_SHA}'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: '${LINUX_AMD64_GLIB_BIN}_v${RUST_APP_VERSION}-${CI_COMMIT_SHORT_SHA}'
          filepath: '/target/x86_64-unknown-linux-gnu/release/mycondominium-backend'
          link_type: 'package'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID_LINUX_AMD64_GNU}/artifacts/raw/target/x86_64-unknown-linux-gnu/release/mycondominium-backend'
        - name: '${LINUX_AMD64_MUSL_BIN}_v${RUST_APP_VERSION}-${CI_COMMIT_SHORT_SHA}'
          filepath: '/target/x86_64-unknown-linux-musl/release/mycondominium-backend'
          link_type: 'package'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID_LINUX_AMD64_MUSL}/artifacts/raw/target/x86_64-unknown-linux-musl/release/mycondominium-backend'

release_main:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $SKIP_BUILD
      when: never
  variables:
    LINUX_AMD64_GLIB_BIN: "mycondominium-server-linux-gnu-amd64"
    LINUX_AMD64_MUSL_BIN: "mycondominium-server-linux-musl-amd64"
  needs:
    job: build
    artifacts: true
  script:
    - if [ $(cat ./.pipeline_re_run_status) == "true" ]; then echo "Skipping because this is a re-run"; exit 0; fi
    - if [ ${SKIP_BUILD} == "true" ]; then echo "Skipping because of SKIP_BUILD set to true"; exit 0; fi
    - echo "LINUX_GNU_AMD64_BIN_URL=${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID_LINUX_AMD64_GNU}/artifacts/raw/target/x86_64-unknown-linux-gnu/release/mycondominium-backend" >> release_main.env
    - echo "LINUX_MUSL_AMD64_BIN_URL=${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID_LINUX_AMD64_MUSL}/artifacts/raw/target/x86_64-unknown-linux-musl/release/mycondominium-backend" >> release_main.env
    - echo "Running release_main for v${RUST_APP_VERSION}"
    - echo -e "## MyCondominium Mainline Build v${RUST_APP_VERSION}\n\n---\n\n### Changelog:\n\n${CI_COMMIT_MESSAGE}" > description.md
    - echo -e "Mainline Build v${RUST_APP_VERSION}" > release_name.txt
  artifacts:
    paths:
      - release_name.txt
  release:
    name: 'Mainline Build v${RUST_APP_VERSION}'
    description: description.md
    tag_name: 'mainline-v${RUST_APP_VERSION}'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: '${LINUX_AMD64_GLIB_BIN}_v${RUST_APP_VERSION}'
          filepath: '/target/x86_64-unknown-linux-gnu/release/mycondominium-backend'
          link_type: 'package'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID_LINUX_AMD64_GNU}/artifacts/raw/target/x86_64-unknown-linux-gnu/release/mycondominium-backend'
        - name: '${LINUX_AMD64_MUSL_BIN}_v${RUST_APP_VERSION}'
          filepath: '/target/x86_64-unknown-linux-musl/release/mycondominium-backend'
          link_type: 'package'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID_LINUX_AMD64_MUSL}/artifacts/raw/target/x86_64-unknown-linux-musl/release/mycondominium-backend'