mod announcement_model;
pub mod prelude;
mod common_area_model;
mod document_model;
mod election_model;
mod incident_model;
mod invoice_model;
mod maintenance_schedule_model;
mod parcel_model;
mod reservation_model;
mod resident_model;
mod vehicle_model;
mod vote_model;